[workspace]
resolver = "2"
members = [
    "examples/conduit-example",
    "packages/*",
]

[workspace.dependencies]
uuid = { version = "1.21.0", features = ["v4"] }
pest = { version = "2.8.6", features = ["pretty-print"] }
pest_derive = { version = "2.8.6" }
thiserror = "2.0.18"
inventory = "0.3.21"
petgraph = "0.8.3"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros", "time", "sync", "fs"] }
conduit = { path = "./packages/conduit" }
async-trait = "0.1.89"
conduit-derive = { path = "./packages/conduit-derive" }
