[package]
name = "conduit-example"
version = "0.1.0"
edition = "2024"

[lib]
name = "example"
crate-type = ["cdylib", "rlib"]

[dependencies]
image = "0.25.9"
async-trait = { workspace = true }
conduit = { workspace = true }
conduit-derive = { workspace = true }
inventory = { workspace = true }
tokio = { workspace = true }

[[example]]
name = "resize_image"

[[example]]
name = "events"

[[example]]
name = "for_loop"
