[package]
name = "conduit-example"
version = "0.1.0"
edition = "2024"

[[example]]
name = "basic"
path = "src/main.rs"

[lib]
name = "conduit_example_lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
image = "0.25.6"
async-trait = { workspace = true }
conduit = { workspace = true }
conduit-derive = { workspace = true }
inventory = { workspace = true }
